INSERT INTO posts (user_id, boat_title, boat_description, boat_price, image_url) VALUES
  (1, 'Ocean Opulence', 'Sail the seas in style with this luxurious yacht, boasting spacious decks and lavish interiors for the ultimate in comfort and elegance.', 2500000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\ocean_opulence.jpg'),
  (2, 'Seafarer''s Dream', 'Embark on unforgettable adventures aboard this sleek and stylish yacht, equipped with state-of-the-art amenities and panoramic views of the open ocean.', 1800000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\seafarers_dream.jpg'),
  (3, 'Aqua Vista', 'Experience the epitome of sophistication on Aqua Vista, featuring opulent staterooms, gourmet dining options, and impeccable craftsmanship throughout.', 3200000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\aqua_vista.jpg'),
  (4, 'Wave Whisperer', 'Cruise in tranquility on Wave Whisperer, a yacht designed for serenity seekers with its serene ambiance, serene deck spaces, and serene sunsets over the horizon.', 1300000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\wave_whisperer.jpg'),
  (5, 'Nautical Nirvana', 'Find your bliss at sea with Nautical Nirvana, where every detail is meticulously crafted for relaxation and enjoyment, from the spacious sundeck to the indulgent spa facilities.', 2700000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\nautical_nirvana.jpg'),
  (6, 'Maritime Majesty', 'Command attention on the open waters with Maritime Majesty, a grand vessel exuding elegance and prestige, perfect for hosting unforgettable gatherings and events.', 3500000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\maritime_majesty.jpg'),
  (7, 'Yachtalicious', 'Indulge in the ultimate yachting experience aboard Yachtalicious, where every moment is filled with luxury, excitement, and endless possibilities for adventure.', 1600000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\yachtalicious.jpg'),
  (8, 'Sailor''s Sanctuary', 'Escape to your personal oasis at sea on Sailor''s Sanctuary, featuring serene hideaways, pristine beaches, and unparalleled views of the azure waters.', 2000000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\sailors_sanctuary.jpg'),
  (9, 'Aquatic Elegance', 'Revel in the timeless beauty of Aquatic Elegance, where classic design meets modern luxury, offering a seamless blend of comfort and sophistication.', 2900000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\aquatic_elegance.jpg'),
  (10, 'Yacht Noir', 'Embark on a journey of intrigue and allure aboard Yacht Noir, where the allure of the open sea meets the mystique of a bygone era, creating an unforgettable experience for the discerning adventurer.', 2400000.00, '\\\\wsl.localhost\\LHL\\home\\labber\\focal\\Midterm\\BeaconBuy\\public\\boats\\yacht_noir.jpg');
